##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://hypersign.id/
# Discord or Telegram project: https://discord.gg/ezJZVjPDDS https://t.me/hypersignchain
# Twitter: https://twitter.com/hypersignchain/
# Explorer: https://exp.nodeist.net/T-Hypersign/staking
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" # Password for are SSH connection.
      - "MONIKER=Akash" # Node name. Use "Akash" in moniker(for example:Dimokus_Akash) to help develop the project! Имя ноды. Используйте в моникере "Akash"(например:Dimokus_Akash) что бы помочь в развитии проекта!
      - "VALIDATOR_KEY_JSON_BASE64=" # 
      - "GITHUB_REPOSITORY=https://github.com/hypersign-protocol/hid-node"
      - "BINARY_VERSION=b910dd6fda612ec8b582ed09ceaa7b6291073966"
      - "GO_VERSION=1.19"
      - "RPC=http://65.108.238.61:56657"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y; apt install -y curl; curl -s https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
