---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS="
      - "VERSION=RC-0.9.2"
      - "KEYFILE_BASE64="
      - "KEY_PASS="
      - "ADDRESS="
      - "CHAINS_LINK="
      - "CHAIN="
      - "SEEDS="
      
    command:
      - "bash"
      - "-c"
    args:
      - "apt-get update && apt-get upgrade -y;apt-get install -y curl;
         curl -s https://raw.githubusercontent.com/DecloudNodesLab/Projects/main/POKT_Network/main.sh | bash"   
    
    expose:
      - port: 8081
        as: 8081
        to:
         - global: true 
      - port: 26656
        as: 26656
        to:
         - global: true 
      - port: 80
        as: 80
        to:
         - global: true 
      - port: 22
        as: 22
        to:
         - global: true 

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 20Gi
         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
