##############################
# Validator node on Akash Network
#
# Guide for deploy node https://docs.declab.pro/guides/cloudmos
# Site project: https://sentinel.co/
# Discord or Telegram project: https://discord.com/invite/mmAA8qF
# Twitter: https://twitter.com/Sentinel_co
# Explorer: https://www.mintscan.io/sentinel
##############################

---
version: "2.0"
services:
  app:
    image: declab/universe:0.1.7
    env:
      - "SSH_KEY="
      - "MONIKER=Akash"
      - "BINARY_LINK=https://github.com/sentinel-official/hub/releases/download/v0.11.3/sentinelhub"
      - "BINARY=sentinelhub"
      - "FOLDER=.sentinelhub"
      - "STATE_SYNC=enable"
      - "DENOM=udvpn"
      - "PEERS=26422b225939a310fe1022730b38149a69d7d97e@38.242.200.201:26656,11dd817e50479f928a52cf16e07dfb0e207a4772@45.77.62.130:26656,66d0d22dc5e1e542c200da1fc097dae5ea1f3b4e@195.201.175.156:17256,01df51c57897e04ebd6492ff8b5944619857f57f@216.128.136.66:26656,ebc272824924ea1a27ea3183dd0b9ba713494f83@195.3.223.168:26706"
      - "RPC=https://rpc.sentinel.co:443"
    expose:
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 100Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1
