##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/DecloudNodesLab/Guides/blob/main/README.md
# Site project: https://sentinel.co/
# Discord or Telegram project: https://discord.com/invite/mmAA8qF
# Twitter: https://twitter.com/Sentinel_co
# Explorer: https://www.mintscan.io/sentinel
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" #Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Akash" # Node name.Имя ноды.
      - "GITHUB_REPOSITORY=https://github.com/sentinel-official/hub.git"
      - "BINARY_VERSION=v0.10.1"
      - "BINARY=sentinelhub"
      - "SNAPSHOT=https://snapshots.autostake.com/sentinelhub-2/sentinelhub-2-Jun-02.tar.lz4"
      - "DENOM=udvpn"
      - "RPC=https://rpc.sentinel.co:443"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update;apt upgrade -y ; apt install -y curl; curl -s  https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 80Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1
