##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://desmos.network/
# Discord or Telegram project: https://discord.desmos.network/
# Twitter: https://twitter.com/DesmosNetwork
# Explorer: https://www.mintscan.io/desmos
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" #Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Powered_by_Akash" # Node name.Имя ноды.
      - "VALIDATOR_KEY_JSON_BASE64=" 
      - "BINARY_LINK=https://github.com/desmos-labs/desmos/releases/download/v5.0.1/desmos-5.0.1-linux-amd64"
      - "BINARY=desmos"
      - "RPC=https://rpc.desmos.forbole.com:443"
      - "PEERS="
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y && apt install -y curl && curl -s https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 3.0
        memory:
          size: 4Gi
        storage:
          size: 100Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
