##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://desmos.network/
# Discord or Telegram project: https://discord.desmos.network/
# Twitter: https://twitter.com/DesmosNetwork
# Explorer: https://www.mintscan.io/desmos
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" 
      - "MONIKER=Akash" 
      - "VALIDATOR_KEY_JSON_BASE64="
      - "SNAPSHOT="
      - "RPC=https://desmos.nodejumper.io:443"
      - "BINARY_LINK=https://github.com/desmos-labs/desmos/releases/download/v5.2.0/desmos-5.2.0-linux-amd64"
      - "BINARY=desmos"
      - "DENOM=udsm"
      - "PEERS=f090ead239426219d605b392314bdd73d16a795f@desmos.nodejumper.io:32656,dfc0639d17b290db7339d16cca2673f7812d4e5f@65.108.4.28:26656,961d438daf13016d580e5809e3255c2aaae928ad@5.9.50.59:22656,b9969966a3d78e4dbc14b836bc0674d7c790df19@142.132.158.93:16256,0e77e62b5c277f85d0845d85c2ea86dd42fc30ff@23.88.74.159:56656,311cfd5691f11ec0cb0f0b8e5303016d86fb4789@148.251.19.41:26656,c0405d5eaaf811ef087d31df9d34ce2aecbe4957@135.181.31.32:26656,9ba7ce8d39b5161fcd6cf2447010bbec42d4692b@141.94.73.39:36756,a68388733297ab7412f4701ef26851b8e5b2243c@178.63.51.118:26656"
      - "DISABLE_FASTNODE=true"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y && apt install -y curl && curl -s https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 3.0
        memory:
          size: 4Gi
        storage:
          size: 80Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
