
##############################
# Empower Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://empowerchain.io/
# Discord or Telegram project: https://discord.gg/9AVrbea6RN
# Twitter: https://twitter.com/empowerchain_io
# Explorer: https://testnet-empower.zenscan.io/index.php
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS="
      - "MONIKER=Akash" 
      - "VALIDATOR_KEY_JSON_BASE64=" 
      - "GITHUB_REPOSITORY=https://github.com/EmpowerPlastic/empowerchain"
      - "RPC=https://empower-testnet.nodejumper.io:443"
      - "SNAPSHOT=https://snapshots2-testnet.nodejumper.io/empower-testnet/circulus-1_2023-06-07.tar.lz4"
      - "BINARY=empowerd"
      - "FOLDER=.empowerchain"
      - "BINARY_LINK=https://github.com/EmpowerPlastic/empowerchain/releases/download/v1.0.0-rc1/empowerd-v1.0.0-rc1-linux-amd64.zip"
      - "GENESIS=https://raw.githubusercontent.com/EmpowerPlastic/empowerchain/main/testnets/circulus-1/genesis.json"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update;apt upgrade -y; apt install curl -y ;curl -s  https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
