##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://humans.ai/
# Discord or Telegram project: https://discord.gg/humansdotai
# Twitter: https://twitter.com/humansdotai
# Explorer: https://explorer.humans.zone/wallet/import
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" #Root password far a ssh connection. Пароль root для подключения по ssh.
      - "MONIKER=Akash" # Node name.Имя ноды.
      #- "VALIDATOR_KEY_JSON_BASE64=" # link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos.
      - "BINARY_LINK=https://github.com/humansdotai/humans/releases/download/v1.0.0/humans_latest_linux_amd64.tar.gz"
      - "BINARY=humansd"
      - "STATE_SYNC=off"
      - "SNAPSHOT=https://snapshots.polkachu.com/testnet-snapshots/humans/humans_1086629.tar.lz4" # Using actual snepshot on https://polkachu.com/testnets/humans/snapshots . Используйте актуальный снепшот на https://polkachu.com/testnets/humans/snapshots .
      - "RPC=https://rpc-testnet.humans.zone:443"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y ; apt install curl -y; curl -s  https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
