##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://realio.network/
# Discord or Telegram project: https://discord.gg/z47AJd72rT
# Twitter: https://twitter.com/realio_network
# Explorer: https://explorer.stavr.tech/realio/staking
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" # password far a ssh connection. Пароль для подключения по ssh.
      - "MONIKER=Akash" # Node name.Имя ноды.
      - "VALIDATOR_KEY_JSON_BASE64=" 
      - "GITHUB_REPOSITORY=https://github.com/realiotech/realio-network"
      - "BINARY_VERSION=v0.7.2"
      - "RPC=https://realio-rpc.42cabi.net:443"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ; apt-get upgrade -y ; apt-get install -y  curl ; curl -s  https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
