##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/DecloudNodesLab/Guides/blob/main/README.md
# Site project: https://akash.network/
# Discord or Telegram project: https://discord.gg/akash
# Twitter: https://twitter.com/akashnet_
# Explorer: https://www.mintscan.io/akash/
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" #Root password far a ssh connection.
      - "MONIKER=Akash" # Node name.
      - "VALIDATOR_KEY_JSON_BASE64=" 
      - "GITHUB_REPOSITORY=https://github.com/ovrclk/akash.git"
      - "BINARY_VERSION=v0.27.0"
      - "GO_VERSION=1.19.1"
      - "RPC=https://rpc-akash.ecostake.com:443"
      - "SNAPSHOT=" # use actual snapshot link https://polkachu.com/tendermint_snapshots/akash
      - "PEERS="
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update;apt upgrade -y; apt install curl -y ;curl -s  https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
