
##############################
# Empower Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://empowerchain.io/
# Discord or Telegram project: https://discord.gg/9AVrbea6RN
# Twitter: https://twitter.com/empowerchain_io
# Explorer: https://testnet-empower.zenscan.io/index.php
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=EmpDim123"
      - "MONIKER=Powered by Akash Network!" 
      - "VALIDATOR_KEY_JSON_BASE64=" 
      - "GITHUB_REPOSITORY=https://github.com/EmpowerPlastic/empowerchain"
      - "GENESIS=https://github.com/EmpowerPlastic/empowerchain/raw/main/mainnet/empowerchain-1/genesis.tar.gz"
      - "RPC=https://empower-rpc.polkachu.com:443"
      - "BINARY=empowerd"
      - "FOLDER=.empowerchain"
      - "CHAIN=empowerchain-1"
      - "DENOM=umpwr"
      - "BINARY_LINK=https://github.com/EmpowerPlastic/empowerchain/releases/download/v1.0.0/empowerd-v1.0.0-linux-amd64.zip"
      - "SEEDS=a1427b456513ab70967a2a5c618d347bc89e8848@seed.empowerchain.io:26656"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update;apt upgrade -y; apt install curl -y ;curl -s  https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
