---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    command:
      - 'bash'
      - '-c'
    args:
      - 'apt-get update && apt-get upgrade -y; apt install -y wget curl unzip tmate; sleep infinity'   
    
    expose:
      - port: 80
        as: 80
        to:
         - global: true 
      - port: 22
        as: 22
        to:
         - global: true 
      - port: 8081
        as: 8081
        to:
         - global: true 

profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 50Gi
         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
