endpoints:
  - api-interface: tendermintrpc
    chain-id: LAV1
    network-address: 0.0.0.0:12345
    node-urls:
      - url: ws://localhost:26657/websocket
      - url: http://localhost:26657
  - api-interface: grpc
    chain-id: LAV1
    network-address: 0.0.0.0:12345
    node-urls: 
      - url: http://localhost:9090
  - api-interface: rest
    chain-id: LAV1
    network-address: 0.0.0.0:12345
    node-urls: 
      - url: http://localhost:1317
