endpoints:
  - api-interface: tendermintrpc
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls:
      - url: http://provider.hurricane.akash.pub:31117
      - url: ws://provider.hurricane.akash.pub:31117/websocket
  - api-interface: grpc
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls: 
      - url: provider.hurricane.akash.pub:32131
  - api-interface: rest
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls: 
      - url: http://provider.hurricane.akash.pub:30072
