endpoints:
  - api-interface: tendermintrpc
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls:
      - url: http://provider.palmito.duckdns.org:330615
      - url: ws://provider.palmito.duckdns.org:330615/websocket
      #- url: http://provider.hurricane.akash.pub:<26657>
      #- url: ws://provider.hurricane.akash.pub:<26657>/websocket
  - api-interface: grpc
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls: 
      - url: provider.palmito.duckdns.org:32340
      #- url: provider.hurricane.akash.pub:<9090>
  - api-interface: rest
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls: 
      - url: http://provider.palmito.duckdns.org:31235
      #- url: http://provider.hurricane.akash.pub:<1317>
