endpoints:
  - api-interface: tendermintrpc
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls:
      - url: http://provider.dcnorse.ddns.net:31051
      - url: ws://provider.dcnorse.ddns.net:31051/websocket
      #- url: http://provider.hurricane.akash.pub:<26657>
      #- url: ws://provider.hurricane.akash.pub:<26657>/websocket
  - api-interface: grpc
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls: 
      - url: provider.dcnorse.ddns.net:32041
      #- url: provider.hurricane.akash.pub:<9090>
  - api-interface: rest
    chain-id: LAV1
    network-address: 
        address: "0.0.0.0:2001"
    node-urls: 
      - url: http://provider.dcnorse.ddns.net:31352
      #- url: http://provider.hurricane.akash.pub:<1317>
