##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/DecloudNodesLab/Guides/blob/main/README.md
# Site project: https://lavanet.xyz/
# Discord or Telegram project: https://discord.com/invite/5VcqgwMmkA
# Twitter: https://twitter.com/lavanetxyz
# Explorer: https://bd.lavanet.xyz/
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" #Root password far a ssh connection.
      - "MONIKER=Akash" # Node name. 
      - "VALIDATOR_KEY_JSON_BASE64=" # Paste your base64 encoded priv_validator_key.json
      - "BINARY_LINK=https://github.com/lavanet/lava/releases/download/v0.16.0/lavad-v0.16.0-linux-amd64"
      - "BINARY=lavad"
      - "RPC=https://lava-testnet-rpc.polkachu.com:443"
      - "SNAPSHOT="
      - "PEERS="
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y && apt install -y curl && curl -s  https://server.gitopia.com/raw/DecloudNodesLab/cosmos-universe/master/codebase/main.sh | bash '
    expose:
      - port: 9090
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
