##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/DecloudNodesLab/Guides/blob/main/README.md
# Site project: https://gitopia.com/
# Discord or Telegram project: https://discord.gg/WT2bPyJYF3
# Twitter: https://twitter.com/gitopiaDAO
# Explorer: https://exp.utsa.tech/gitopia-test
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" 
      - "MONIKER=Akash" 
      - "VALIDATOR_KEY_JSON_BASE64="
      - "BINARY_LINK=https://server.gitopia.com/releases/Gitopia/gitopia/v2.1.1/gitopiad_2.1.1_linux_amd64.tar.gz"
      - "RPC=https://gitopia-rpc.polkachu.com:443"
      - "GENESIS=https://snapshots.polkachu.com/genesis/gitopia/genesis.json"
      - "DENOM=ulore"
      - "DISABLE_FASTNODE=true"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y && apt install -y curl && curl -s https://server.gitopia.com/raw/DecloudNodesLab/cosmos-universe/master/codebase/main.sh | bash '
    expose:
      - port: 22
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 26657
        as: 80
        to:
          - global: true       
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 5.0
        memory:
          size: 8Gi
        storage:
          size: 200Gi         
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
