##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://kyve.network/
# Discord or Telegram project: https://discord.gg/kyve
# Twitter: https://twitter.com/KYVENetwork
# Explorer: https://www.mintscan.io/kyve/validators
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS="
      - "MONIKER=Akash" 
      - "VALIDATOR_KEY_JSON_BASE64=" 
      - "GITHUB_REPOSITORY=https://github.com/KYVENetwork/chain.git"
      - "DENOM=ukyve"
      - "SNAPSHOT=https://snapshots.ezstaking.xyz/snapshots/kyve/kyve_03-15-2023_15-42-57.tar.lz4"
      - "RPC=https://rpc-eu-1.kyve.network:443"
      - "STATE_SYNC=off"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y && apt install -y curl && curl -s https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash:       
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
     
