##############################
# Validator node on Akash Network
#
# Guide for deploy node https://github.com/Dimokus88/Akash-Nodes-Lab/blob/main/Guide/README.md
# Site project: https://www.sourceprotocol.io/
# Discord or Telegram project: https://discord.gg/zj8xxUCeZQ
# Twitter: https://www.twitter.com/sourceprotocol_
# Explorer: https://exp.nodeist.net/Source
##############################
# Akash Discord: https://discord.gg/ybKMsYYZkx
# Akash Telegram EN: https://t.me/AkashNW
# Akash Telegram RU: https://t.me/akash_ru
##############################
---
version: "2.0"
services:
  app:
    image: ubuntu:22.04
    env:
      - "SSH_PASS=" # Password for SSH connection.
      - "MONIKER=Akash" # Node name.Имя ноды.
      #- "VALIDATOR_KEY_JSON_BASE64=" # BASE64 encrypted validator key.
      - "GITHUB_REPOSITORY=https://github.com/Source-Protocol-Cosmos/source.git"
      - "RPC=http://rpc.source.ppnv.space:22657"
    command:
      - "bash"
      - "-c"
    args:
      - 'apt update && apt upgrade -y ; apt install curl -y; curl -s  https://raw.githubusercontent.com/DecloudNodesLab/CodeBase/main/deploy/main_cosmossdk.sh | bash '
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
          size: 200Gi
  placement:
    akash: 
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
